#!/usr/bin/env python3
"""
setup_pi.py — Pi Server Setup
Run this once on your Raspberry Pi to configure and install the server and dashboard.

Usage:
    python3 setup_pi.py

What it does:
    1. Asks for your configuration (IP, port, etc.)
    2. Generates server.py  — Flask backend that receives device data
    3. Generates dashboard.py — Fullscreen dark tkinter dashboard
    4. Installs systemd services so both start automatically on boot
"""

import os
import sys
import subprocess
import socket


# ── helpers ───────────────────────────────────────────────────────────────────

def ask(prompt, default=None):
    suffix = f" [{default}]" if default else ""
    val = input(f"  {prompt}{suffix}: ").strip()
    return val if val else default

def section(title):
    print()
    print("=" * 60)
    print(f"  {title}")
    print("=" * 60)

def write_file(path, content):
    with open(path, "w") as f:
        f.write(content)
    print(f"  [+] Written: {path}")

def run(cmd, check=True):
    subprocess.run(cmd, shell=True, check=check)


# ── detect local IP ───────────────────────────────────────────────────────────

def get_local_ip():
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        return "0.0.0.0"


# ── gather config ─────────────────────────────────────────────────────────────

section("Pi Server Setup")
print("""
  This script will configure your Raspberry Pi as the central
  server and dashboard for the Task Manager RAT system.
""")

local_ip = get_local_ip()

print("  Enter your configuration below.")
print("  Press Enter to accept the [default] value.\n")

SERVER_IP   = ask("Pi IP address (for clients to connect to)", local_ip)
SERVER_PORT = ask("Server port", "5000")
POLL_INTERVAL = ask("How often should clients send data (seconds)", "5")
INSTALL_DIR = ask("Install directory on this Pi", "/opt/taskmanager")

print()
print("  Configuration summary:")
print(f"    Server IP     : {SERVER_IP}")
print(f"    Server Port   : {SERVER_PORT}")
print(f"    Poll interval : {POLL_INTERVAL}s")
print(f"    Install dir   : {INSTALL_DIR}")
print()
confirm = input("  Looks good? (y/n): ").strip().lower()
if confirm != "y":
    print("  Aborted.")
    sys.exit(0)


# ── install dependencies ──────────────────────────────────────────────────────

section("Installing Dependencies")
run("sudo apt update -y")
run("sudo apt install python3 python3-pip python3-tk -y")
run("sudo pip3 install flask --break-system-packages")
run(f"sudo mkdir -p {INSTALL_DIR}")
run(f"sudo chown $USER:$USER {INSTALL_DIR}")


# ── generate server.py ────────────────────────────────────────────────────────

section("Generating server.py")

SERVER_CODE = f'''#!/usr/bin/env python3
"""
server.py — Flask backend (auto-generated by setup_pi.py)
Receives process data from client devices and serves it to the dashboard.
"""

from flask import Flask, request, jsonify
import threading
import time

app = Flask(__name__)

# device_id -> {{ip, process_count, processes, last_seen, pending_command}}
devices = {{}}
lock = threading.Lock()

TIMEOUT = 30  # seconds before a device is considered offline


@app.route("/device", methods=["POST"])
def update_device():
    data = request.get_json()
    if not data:
        return jsonify({{"error": "no data"}}), 400

    device_id = data.get("device_id")
    if not device_id:
        return jsonify({{"error": "no device_id"}}), 400

    with lock:
        pending = devices.get(device_id, {{}}).get("pending_command")
        devices[device_id] = {{
            "ip":            request.remote_addr,
            "process_count": data.get("process_count", 0),
            "processes":     data.get("processes", []),
            "last_seen":     time.time(),
            "pending_command": None,  # clear after sending
        }}

    response = {{}}
    if pending:
        response["command"] = pending

    return jsonify(response)


@app.route("/devices", methods=["GET"])
def list_devices():
    now = time.time()
    with lock:
        result = {{}}
        for dev_id, info in devices.items():
            result[dev_id] = {{
                "ip":            info["ip"],
                "process_count": info["process_count"],
                "processes":     info["processes"],
                "online":        (now - info["last_seen"]) < TIMEOUT,
                "last_seen":     info["last_seen"],
            }}
    return jsonify(result)


@app.route("/command", methods=["POST"])
def send_command():
    data = request.get_json()
    device_id = data.get("device_id")
    command    = data.get("command")
    target     = data.get("target")

    if not device_id or not command:
        return jsonify({{"error": "missing fields"}}), 400

    with lock:
        if device_id not in devices:
            return jsonify({{"error": "device not found"}}), 404
        devices[device_id]["pending_command"] = {{
            "command": command,
            "target":  target,
        }}

    return jsonify({{"status": "queued"}})


if __name__ == "__main__":
    print(f"[*] Task Manager Server running on {SERVER_IP}:{SERVER_PORT}")
    app.run(host="0.0.0.0", port={SERVER_PORT}, debug=False)
'''

write_file(f"{INSTALL_DIR}/server.py", SERVER_CODE)


# ── generate dashboard.py ─────────────────────────────────────────────────────

section("Generating dashboard.py")

DASHBOARD_CODE = f'''#!/usr/bin/env python3
"""
dashboard.py — Fullscreen dark tkinter dashboard (auto-generated by setup_pi.py)
Displays all connected devices and their processes in real time.
"""

import tkinter as tk
from tkinter import ttk, messagebox
import requests
import threading
import time

SERVER = "http://127.0.0.1:{SERVER_PORT}"
REFRESH_MS = {int(POLL_INTERVAL) * 1000}

# ── colour palette ────────────────────────────────────────────────────────────
BG          = "#0f172a"
CARD_BG     = "#1e293b"
CARD_BORDER = "#334155"
ACCENT      = "#3b82f6"
DANGER      = "#ef4444"
SUCCESS     = "#22c55e"
TEXT        = "#f1f5f9"
SUBTEXT     = "#94a3b8"
FONT_TITLE  = ("Segoe UI", 22, "bold")
FONT_HEAD   = ("Segoe UI", 13, "bold")
FONT_BODY   = ("Segoe UI", 11)
FONT_SMALL  = ("Segoe UI", 9)
FONT_MONO   = ("Consolas", 10)


class Dashboard(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Task Manager — Device Dashboard")
        self.configure(bg=BG)
        self.attributes("-fullscreen", True)
        self.bind("<Escape>", lambda e: self.attributes("-fullscreen", False))
        self.bind("<F11>",    lambda e: self.attributes("-fullscreen", True))

        self.devices = {{}}
        self.selected_device = None
        self._build_ui()
        self._refresh()

    # ── UI layout ─────────────────────────────────────────────────────────────

    def _build_ui(self):
        # top bar
        topbar = tk.Frame(self, bg="#0b1120", pady=14)
        topbar.pack(fill="x")

        tk.Label(topbar, text="⬡  Task Manager", font=FONT_TITLE,
                 bg="#0b1120", fg=TEXT).pack(side="left", padx=24)

        self.status_lbl = tk.Label(topbar, text="Connecting...",
                                   font=FONT_SMALL, bg="#0b1120", fg=SUBTEXT)
        self.status_lbl.pack(side="right", padx=24)

        tk.Label(topbar, text="ESC = exit fullscreen  |  F11 = fullscreen",
                 font=FONT_SMALL, bg="#0b1120", fg=SUBTEXT).pack(side="right", padx=8)

        # main area: device list (left) + process panel (right)
        main = tk.Frame(self, bg=BG)
        main.pack(fill="both", expand=True, padx=20, pady=16)

        # left — device cards
        left = tk.Frame(main, bg=BG, width=320)
        left.pack(side="left", fill="y", padx=(0, 16))
        left.pack_propagate(False)

        tk.Label(left, text="DEVICES", font=FONT_SMALL,
                 bg=BG, fg=SUBTEXT).pack(anchor="w", pady=(0, 8))

        self.device_frame = tk.Frame(left, bg=BG)
        self.device_frame.pack(fill="both", expand=True)

        # right — process list
        right = tk.Frame(main, bg=BG)
        right.pack(side="left", fill="both", expand=True)

        proc_header = tk.Frame(right, bg=BG)
        proc_header.pack(fill="x", pady=(0, 8))

        tk.Label(proc_header, text="PROCESSES", font=FONT_SMALL,
                 bg=BG, fg=SUBTEXT).pack(side="left")

        self.proc_search_var = tk.StringVar()
        self.proc_search_var.trace("w", lambda *a: self._filter_processes())
        search = tk.Entry(proc_header, textvariable=self.proc_search_var,
                          bg=CARD_BG, fg=TEXT, insertbackground=TEXT,
                          relief="flat", font=FONT_BODY, width=24)
        search.pack(side="right", ipady=4, ipadx=6)
        tk.Label(proc_header, text="Search:", font=FONT_SMALL,
                 bg=BG, fg=SUBTEXT).pack(side="right", padx=(0, 6))

        # process listbox
        list_frame = tk.Frame(right, bg=CARD_BG, bd=0)
        list_frame.pack(fill="both", expand=True)

        scrollbar = tk.Scrollbar(list_frame)
        scrollbar.pack(side="right", fill="y")

        self.proc_list = tk.Listbox(
            list_frame, bg=CARD_BG, fg=TEXT, font=FONT_MONO,
            selectbackground=ACCENT, selectforeground=TEXT,
            relief="flat", bd=0, highlightthickness=0,
            yscrollcommand=scrollbar.set, activestyle="none",
        )
        self.proc_list.pack(fill="both", expand=True, padx=4, pady=4)
        scrollbar.config(command=self.proc_list.yview)

        # end task button
        btn_frame = tk.Frame(right, bg=BG)
        btn_frame.pack(fill="x", pady=(10, 0))

        self.end_btn = tk.Button(
            btn_frame, text="⏹  End Task", font=FONT_HEAD,
            bg=DANGER, fg=TEXT, relief="flat", bd=0,
            activebackground="#b91c1c", activeforeground=TEXT,
            padx=20, pady=10, cursor="hand2",
            command=self._end_task,
        )
        self.end_btn.pack(side="right")

        self.proc_device_lbl = tk.Label(
            btn_frame, text="Select a device to view processes",
            font=FONT_BODY, bg=BG, fg=SUBTEXT,
        )
        self.proc_device_lbl.pack(side="left")

    # ── device cards ──────────────────────────────────────────────────────────

    def _rebuild_device_cards(self):
        for w in self.device_frame.winfo_children():
            w.destroy()

        if not self.devices:
            tk.Label(self.device_frame, text="No devices connected",
                     font=FONT_BODY, bg=BG, fg=SUBTEXT).pack(pady=20)
            return

        for dev_id, info in self.devices.items():
            self._make_card(dev_id, info)

    def _make_card(self, dev_id, info):
        online  = info.get("online", False)
        dot_col = SUCCESS if online else DANGER
        status  = "Online" if online else "Offline"

        card = tk.Frame(self.device_frame, bg=CARD_BG, bd=0,
                        highlightthickness=2,
                        highlightbackground=ACCENT if dev_id == self.selected_device else CARD_BORDER)
        card.pack(fill="x", pady=5)

        inner = tk.Frame(card, bg=CARD_BG, padx=14, pady=12)
        inner.pack(fill="x")

        # dot + name
        top = tk.Frame(inner, bg=CARD_BG)
        top.pack(fill="x")
        tk.Label(top, text="●", font=FONT_BODY, bg=CARD_BG, fg=dot_col).pack(side="left")
        tk.Label(top, text=f"  {{dev_id}}", font=FONT_HEAD, bg=CARD_BG, fg=TEXT).pack(side="left")

        # ip + process count
        tk.Label(inner, text=f"IP: {{info.get('ip', '?')}}   |   {{info.get('process_count', 0)}} processes",
                 font=FONT_SMALL, bg=CARD_BG, fg=SUBTEXT).pack(anchor="w", pady=(4, 0))

        # click to select
        for widget in [card, inner] + list(inner.winfo_children()) + list(top.winfo_children()):
            widget.bind("<Button-1>", lambda e, d=dev_id: self._select_device(d))

    # ── process list ──────────────────────────────────────────────────────────

    def _select_device(self, dev_id):
        self.selected_device = dev_id
        self._update_process_panel()
        self._rebuild_device_cards()

    def _update_process_panel(self):
        if not self.selected_device or self.selected_device not in self.devices:
            self.proc_device_lbl.config(text="Select a device to view processes")
            self.proc_list.delete(0, "end")
            return

        info = self.devices[self.selected_device]
        count = info.get("process_count", 0)
        self.proc_device_lbl.config(
            text=f"{{self.selected_device}}  —  {{count}} processes  ({{info.get('ip', '?')}})"
        )
        self._filter_processes()

    def _filter_processes(self):
        if not self.selected_device or self.selected_device not in self.devices:
            return
        query = self.proc_search_var.get().lower()
        procs = self.devices[self.selected_device].get("processes", [])
        filtered = [p for p in procs if query in p.lower()] if query else procs

        self.proc_list.delete(0, "end")
        for p in sorted(filtered):
            self.proc_list.insert("end", f"  {{p}}")

    # ── end task ──────────────────────────────────────────────────────────────

    def _end_task(self):
        if not self.selected_device:
            messagebox.showwarning("No Device", "Please select a device first.")
            return
        sel = self.proc_list.curselection()
        if not sel:
            messagebox.showwarning("No Process", "Please select a process to end.")
            return

        proc_name = self.proc_list.get(sel[0]).strip()
        if not messagebox.askyesno("Confirm", f"End task '{{proc_name}}' on {{self.selected_device}}?"):
            return

        try:
            requests.post(f"{{SERVER}}/command", json={{
                "device_id": self.selected_device,
                "command":   "end_task",
                "target":    proc_name,
            }}, timeout=5)
            self.proc_list.delete(sel[0])
        except Exception as e:
            messagebox.showerror("Error", f"Failed to send command:\\n{{e}}")

    # ── refresh loop ──────────────────────────────────────────────────────────

    def _refresh(self):
        threading.Thread(target=self._fetch, daemon=True).start()
        self.after(REFRESH_MS, self._refresh)

    def _fetch(self):
        try:
            r = requests.get(f"{{SERVER}}/devices", timeout=5)
            self.devices = r.json()
            self.after(0, self._on_data)
        except Exception as e:
            self.after(0, lambda: self.status_lbl.config(
                text=f"Server unreachable — retrying...", fg=DANGER))

    def _on_data(self):
        online = sum(1 for d in self.devices.values() if d.get("online"))
        total  = len(self.devices)
        self.status_lbl.config(
            text=f"{{online}}/{{total}} devices online  •  Last updated: {{time.strftime('%H:%M:%S')}}",
            fg=SUCCESS if online else SUBTEXT,
        )
        self._rebuild_device_cards()
        self._update_process_panel()


if __name__ == "__main__":
    app = Dashboard()
    app.mainloop()
'''

write_file(f"{INSTALL_DIR}/dashboard.py", DASHBOARD_CODE)


# ── generate client config template ──────────────────────────────────────────

section("Generating client Config template")

CONFIG_TEMPLATE = f"""SERVER_IP={SERVER_IP}
SERVER_PORT={SERVER_PORT}
DEVICE_ID=MyDevice
POLL_INTERVAL={POLL_INTERVAL}
"""

write_file(f"{INSTALL_DIR}/Config.template.txt", CONFIG_TEMPLATE)
print("  [i] Clients will need their own Config.txt based on this template.")


# ── systemd services ──────────────────────────────────────────────────────────

section("Installing systemd Services")

USER = os.environ.get("USER", "pi")
DISPLAY_ENV = ":0"

SERVER_SERVICE = f"""[Unit]
Description=Task Manager — Flask Server
After=network.target

[Service]
ExecStart=/usr/bin/python3 {INSTALL_DIR}/server.py
WorkingDirectory={INSTALL_DIR}
Restart=always
RestartSec=5
User={USER}
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
"""

DASHBOARD_SERVICE = f"""[Unit]
Description=Task Manager — Dashboard
After=graphical.target taskmanager-server.service
Requires=taskmanager-server.service

[Service]
ExecStart=/usr/bin/python3 {INSTALL_DIR}/dashboard.py
WorkingDirectory={INSTALL_DIR}
Restart=always
RestartSec=5
User={USER}
Environment=DISPLAY={DISPLAY_ENV}
Environment=XAUTHORITY=/home/{USER}/.Xauthority

[Install]
WantedBy=graphical.target
"""

write_file("/tmp/taskmanager-server.service", SERVER_SERVICE)
write_file("/tmp/taskmanager-dashboard.service", DASHBOARD_SERVICE)

run("sudo cp /tmp/taskmanager-server.service /etc/systemd/system/")
run("sudo cp /tmp/taskmanager-dashboard.service /etc/systemd/system/")
run("sudo systemctl daemon-reload")
run("sudo systemctl enable taskmanager-server")
run("sudo systemctl enable taskmanager-dashboard")
run("sudo systemctl start taskmanager-server")
run("sudo systemctl start taskmanager-dashboard")


# ── done ──────────────────────────────────────────────────────────────────────

section("Setup Complete")
print(f"""
  Files installed to : {INSTALL_DIR}/
    server.py          — Flask backend
    dashboard.py       — Fullscreen dashboard
    Config.template.txt — Template for client Config.txt

  Services installed and started:
    taskmanager-server     (Flask API on port {SERVER_PORT})
    taskmanager-dashboard  (Fullscreen tkinter UI)

  Useful commands:
    sudo systemctl status taskmanager-server
    sudo systemctl status taskmanager-dashboard
    sudo journalctl -u taskmanager-server -f
    sudo journalctl -u taskmanager-dashboard -f

  Give clients this info:
    Server IP   : {SERVER_IP}
    Server Port : {SERVER_PORT}
    Poll interval: {POLL_INTERVAL}s
""")
